### ISSUE TITLE
Group Discussion: Theory in Network Neuroscience

### ISSUE THREAD

**Issue by danlurie** [ohbm/OpenScienceRoom2019#11]
**Topic**
Theoretical considerations when applying graph theory approaches to the analysis of neuroscience data.

**Main organiser**
Dan Lurie (@danlurie)

**Preferred time slots**
Tuesday 1700-1800
Wednesday 1815-1915

**Tag other attendees**
Lots. I could only find Github accounts for a fraction of those who have expressed interest in participating. These include @simonwdavis, @cMadan, @pbellec, @macshine, @danielemarinazzo, @complexbrains, and @mwcole.

**Open to all?**
Yes!

**Additional Context**
Inspired by a twitter thread started by @pbellec: https://twitter.com/pierre_bellec/status/1121401953916006401

#

Bookings will be coordinated by @TimVanMourik. The schedule is available [here](https://calendar.google.com/calendar?cid=anJjNGh1dXFtODkyazVpbzk3OXF2YmM2N29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

**Comment by danlurie** [comment]
The preferred times I listed are assuming that the OSR will stay open during the evening poster sessions. @TimVanMourik can you confirm whether that is indeed the case?

**Comment by raamana** [comment]
Joining in :)

**Comment by typically** [comment]
Won't be at OHBM, but happy to chip in remotely if that's a thing... (Andrew Reid)

**Comment by wiheto** [comment]
I’ll join (if I make it to Rome)
/William Thompson

**Comment by cMadan** [comment]
I won't be at OHBM this year, but happy to be involved remotely!

**Comment by jennyrobinson** [comment]
I’m in!

**Comment by adeelrazi** [comment]
Great will join..

**Comment by mnarayan** [comment]
Will join

**Comment by danielemarinazzo** [comment]
cool, see you there

**Comment by cryptofan** [comment]
I would definitely like to drop by and watch how you manage this project Dan :)

**Comment by vidaurre** [comment]
I will drop by too!

**Comment by dominikkraft** [comment]
see you there!

**Comment by dcmoyer** [comment]
Sounds great, I plan on being there =)

**Comment by jbrown81** [comment]
Count me in.

**Comment by lindadouw** [comment]
Good idea!

**Comment by emdupre** [comment]
> The preferred times I listed are assuming that the OSR will stay open during the evening poster sessions. @TimVanMourik can you confirm whether that is indeed the case?

@danlurie the OSR will technically be open throughout the conference, but the OSSIG isn't scheduling events then. You can coordinate your own session, of course -- this one seems like a great fit ! :smile_cat:

**Comment by matteogithub** [comment]
Happy to join remotely if possible.

**Comment by dankessler** [comment]
I too am interested in participating remotely

**Comment by ChristophePhillips** [comment]
Would happily join the discussion. :-)

**Comment by asoroosh** [comment]
I'd love to join too.

**Comment by TimVanMourik** [comment]
I added this meeting to the [agenda](https://calendar.google.com/calendar/embed?src=jrc4huuqm892k5io979qvbc67o%40group.calendar.google.com&ctz=Europe%2FAmsterdam) for **Tuesday 17:00-18:00** (June 11th).

**Comment by jesusmcortes** [comment]
I will also attend. thanks to daniele marinazzo for telling me.

**Comment by slieped** [comment]
Count me in! Thanks for this :)

**Comment by TimVanMourik** [comment]
Closing this discussion issue, but feel free to add more content, links, or documents (PR) to document what's been discussed!
