### ISSUE TITLE
Introducing Bioimage Suite Web

### ISSUE THREAD

**Issue by SNeuroble** [ohbm/OpenScienceRoom2019#13]
[![Logo](https://github.com/bioimagesuiteweb/bisweb/raw/master/web/images/bisweb_newlogo_white_small.png)](http://www.bioimagesuite.org/)

---

**Title**
Introducing Bioimage Suite Web: A Simple, Modern, & Powerful Imaging Software Suite

**Presentor and Affiliation**
Stephanie Noble (@SNeuroble), Yale University

**Collaborators/Team**
Zachariah Saltzman (@zsaltzman), Cheryl Lacadie, Haley Garbus, Javid Dadashkarimi (@dadashkarimi), Stephanie Noble (@SNeuroble), John Onofrey, Xenophon Papademetris (@XeniosP)\*, Dustin Scheinost (@dscheinost)\*
Yale University
\* PI and lead developer

**Github Link**
https://github.com/bioimagesuiteweb/bisweb

**Abstract (max. 200 words):**
This demo will introduce users to image processing and visualization in BioImage Suite Web (BISWeb; https://bioimagesuiteweb.github.io/webapp/). BISWeb is a point-and-click app that runs in any modern web browser and most devices without any installation necessary, yet with performance rivaling that of a locally installed software. BISWeb currently supports a range of functionality for image processing, visualization, and data sharing in human and animal fMRI: defacing, segmentation, registration, functional connectivity visualization, live figures, and more. We will highlight the use of live figures, which save the full state of the application and data for a user to return to later or share with collaborators. This information may be used to support future validation of both the analysis and the software (e.g., across versions). 

**Preferred Session**
Web-based solutions in neuroscience; Tuesday or Wednesday

**Additional Context**

*References*
BISWeb app: www.bioimagesuite.org
Github repository: https://github.com/bioimagesuiteweb/bisweb/
Video tutorials: https://www.youtube.com/channel/UCizfR_ryJ0E-2uZspjwYtwg
User documentation: https://bioimagesuiteweb.github.io/bisweb-manual/
Developer documentation: https://github.com/bioimagesuiteweb/bisweb/blob/master/docs/README.md
Link to download desktop/command line version of BIS: http://bisweb.yale.edu/binaries/

*Developer Info*
BISWeb is written primarily in JavaScript, and computationally intensive processing via C++ is accomplished by leveraging WebAssembly to make low-level C++ code accessible to web-based applications. All code associated with BISWeb is and will remain openly available.

**Comment by TimVanMourik** [comment]
Hi @SNeuroble, I’m happy to tell you that we’d like to host your presentation as a demo/tutorial talk in the OSR in the **Web-based solutions for neuroscience** session. This will be a talk of 20 minutes + 5 minutes of questions. We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit slides and other presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master/) by means of a Pull Request to this repository, preferably but not necessarily before the presentation.

**Comment by TimVanMourik** [comment]
Presentation uploaded in #37
