### ISSUE TITLE
Neuroquery: mapping text to brain regions.

### ISSUE THREAD

**Issue by jeromedockes** [ohbm/OpenScienceRoom2019#17]
**Title**

[Neuroquery](https://neuroquery.saclay.inria.fr/query?text=familiar+face+recognition): mapping text to brain regions.

**Presentor and Affiliation**

Jérôme Dockès, INRIA (@jeromedockes)

**Collaborators**

Russel Poldrack, Stanford University
Fabian Suchanek, Telecom Paris
Bertrand Thirion, INRIA (@bthirion)
Gaël Varoquaux, INRIA (@GaelVaroquaux)

**Github Link (if applicable)**

Python package to be released on Github in the near future; but the tool is already online: https://neuroquery.saclay.inria.fr

**Abstract (max. 200 words):**

[Neuroquery](https://neuroquery.saclay.inria.fr/query?text=language) is a new tool for large-scale meta-analysis based on multivariate regression and distributional semantics. It is inspired by [Neurosynth](http://neurosynth.org/), but presents key differences:

- It expands queries to related terms. Existing meta-analysis methods rely on a fixed vocabulary and can only produce brain maps for a restricted set of expressions. Neuroquery relies on co-occurrences in the literature to automatically map user queries to the set of terms it can encode into brain images. It can thus produce maps for a much wider and more flexible set of queries, greatly reducing the need for users to manually adjust their questions to the tool's vocabulary.

- It can encode rare expressions (e.g ["prosopagnosia"](https://neuroquery.saclay.inria.fr/query?text=prosopagnosia)) that are challenging for traditional meta-analysis methods. 

- Rather than single words, it can encode text of arbitrary length. It can produce meaningful maps for concepts that are better described by a [sentence](https://neuroquery.saclay.inria.fr/query?text=reading%2C+understanding+and+performing+a+mental+computation) or paragraph, or even for abstracts or papers.
    
- It models the similarities and relationships between terms used in neuroscience publications, allowing users to easily navigate from a query to related terms and documents and comparing their associated brain maps.

**Preferred Session**

Lightning talk, preferably: "1. Neuroscience toolkit" or "2. Multi-modal research".

**Additional Context**

A more comprehensive description of the methods behind Neuroquery, and extensive empirical validation, will be presented during the oral session "Modeling and Analysis Methods - Uni/multi-variate analysis", on Monday, June 10:

  4554 - Towards Universal Brain Encoding with Multivariate Regression and Large Scientific Corpora
  
At the Open Science Room, I would like to show the online tool and its features, and receive questions and suggestions from potential users and contributors.

**Comment by TimVanMourik** [comment]
Hi @jeromedockes, I’m happy to tell you that we’d like to host your lightning talk in the OSR in the **neuroscience toolkit** session. This will be a talk of 5 minutes + 5 minutes of questions. We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit slides and other presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master/ by means of a Pull Request to this repository, preferably but not necessarily before the presentation.

**Comment by jeromedockes** [comment]
Thanks! I'm planning an interactive demo of a web-based tool so I probably won't have any material to upload.

**Comment by emdupre** [comment]
It would be great if you could upload just a markdown file with the links, so we have a record of what was shown ! If that won't be possible, let us know and we can try to find another solution :smile_cat: Thanks !

**Comment by jeromedockes** [comment]
sure! #34

**Comment by TimVanMourik** [comment]
Thanks for the presentation!

Uploaded in #34
