### ISSUE TITLE
The developing Human Connectome Project automated functional processing framework for neonates 

### ISSUE THREAD

**Issue by SeanFitzgibbon** [ohbm/OpenScienceRoom2019#24]
**Presentor and Affiliation**
Sean Fitzgibbon, WIN@FMRIB, University of Oxford
Eugene Duff, WIN@FMRIB, University of Oxford

**Collaborators**
Wellcome Centre for Integrative Neuroimaging (WIN), University of Oxford
Biomedical Image Analysis Group, Imperial College London 
Centre for the Developing Brain, King's College London

**Github Link (if applicable)**
To be advised.

**Abstract (max. 200 words):**
Neonates present significant challenges to data processing due to rapid developmental changes, low and variable contrast, and high levels of head motion. The dHCP neonatal fMRI pre-processing pipeline has been designed specifically to address the challenges of neonatal data.  The pipeline includes integrated dynamic distortion and slice-to-volume motion correction, a robust multimodal registration approach including custom neonatal templates, bespoke ICA-based denoising, and an automated QC framework.  The pipeline currently has partial BIDS derivatives support with full support under development.  

The pipeline has been evaluated on more than 500 neonatal subjects from the dHCP.  With the impending open release of the pipeline and the pre-processed data by the consortium, now is the ideal time to demonstrate the capabilities of the pipeline to the community.

**Preferred Session**
3. Demo: New advances in open neuroimaging methods

**Comment by TimVanMourik** [comment]
Hi @SeanFitzgibbon, I’m happy to tell you that we’d like to host your presentation as a demo/tutorial talk in the OSR in the **Demo: New advances in open neuroimaging methods** session. This will be a talk of 20 minutes + 5 minutes of questions. We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit slides and other presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master/) by means of a Pull Request to this repository, preferably but not necessarily before the presentation. As we are quite committed to open code and open data, we would like to ask you to make sure to include a GitHub link to the code and to mention a data sharing policy in your presentation.

**Comment by TimVanMourik** [comment]
Presentation uploaded in #42
