### ISSUE TITLE
AFQ-Browser: A browser-based tool for visualization, analysis, and sharing of diffusion MRI data

### ISSUE THREAD

**Issue by richford** [ohbm/OpenScienceRoom2019#26]
**Title**
AFQ-Browser: A browser-based tool for visualization, analysis, and sharing of diffusion MRI data

**Presentor and Affiliation**
Adam Richie-Halford, University of Washington, @richford
Ariel Rokem, University of Washington, @arokem

**Collaborators**
Jason Yeatman, Stanford University, @jyeatman
Anisha Keshavan, Child Mind Institute, @akeshavan 
Joshus K. Smith, University of Washingtojn, @anotherjoshsmith

**Github Link**
[AFQ-Browser](https://github.com/yeatmanlab/AFQ-Browser)

**Abstract (max. 200 words):**
Human neuroscience research faces several challenges with regards to reproducibility. While scientists are generally aware that data sharing is important, it is not always clear how to share data in a manner that allows other labs to understand and reproduce published findings. We will demonstrate a new tool, AFQ-Browser, that builds an interactive website as a companion to a diffusion MRI study. Because AFQ-Browser is portable—it runs in any web-browser—it can facilitate transparency and data sharing. By leveraging new web-visualization technologies to create linked views between different dimensions of the dataset (anatomy, diffusion metrics, subject metadata), AFQ-Browser facilitates exploratory data analysis, fueling new discoveries based on previously published datasets. In an era where Big Data is playing an increasingly prominent role in scientific discovery, so will browser-based tools for exploring high-dimensional datasets, communicating scientific discoveries, aggregating data across labs, and publishing data alongside manuscripts.

**Preferred Session**
1. Demo: New advances in open neuroimaging methods
2. Talk: Web-based solutions in neuroscience
3. Lightning Talk: Neuroscience toolkit

**Additional Context**
[Nature Communications **9**, Article number: 940 (2018)](https://www.nature.com/articles/s41467-018-03297-7)

**Comment by TimVanMourik** [comment]
Hi @richford, I’m happy to tell you that we’d like to host your presentation as a demo/tutorial in the OSR in the **Web-based solutions in neuroscience** session. This will be a talk of 20 minutes + 5 minutes of questions. We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit slides and other presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master) by means of a Pull Request to this repository, preferably but not necessarily before the presentation.

**Comment by arokem** [comment]
Hi @TimVanMourik! That's great! 

The slides for our presentation are coming together here: https://arokem.github.io/2019-OHBM-AFQ-Browser/. Would you like us to add that link to the README file?

**Comment by TimVanMourik** [comment]
Yes please! Ideally a new ReadMe in the `presentations/AFQ-browser_arokem` folder, such that the format is consistent 🙂
