### ISSUE TITLE
BIDScoin: an easy toolkit to convert your data to BIDS

### ISSUE THREAD

**Issue by marcelzwiers** [ohbm/OpenScienceRoom2019#28]
# BIDScoin: an easy toolkit to convert your data to BIDS

Marcel Zwiers<sup>1</sup>, Rutger van Deelen<sup>1</sup>
<sup>1</sup>Donders Institute for Brain, Cognition and Behaviour, Radboud University Nijmegen, The Netherlands

[https://github.com/Donders-Institute/bidscoin](https://github.com/Donders-Institute/bidscoin)

## Abstract
BIDScoin is new open-source python toolkit that converts ("coins") source-level (raw) neuroimaging data-sets according to BIDS. Rather then depending on complex or ambiguous programmatic logic, BIDScoin uses a customizable key-value mapping to convert the raw source data into BIDS data. The key values that can be used in BIDScoin to map the data are:

1. Information in raw MRI data files (e.g. DICOM “SeriesDescription” field)
2. Information from nifti headers (e.g. image dimensionality)
3. Information in the file structure (e.g. filename or number of files)

The key-value heuristics, i.e. the “bidsmaps”, can be entered using a graphical user-interface and are are stored as short YAML-files, which are easy to read and edit both by humans and computers. Compared to existing tools, BIDScoin has the advantage that it is very flexible, user-friendly, requires no programming knowledge or efforts, and can make use of multiple sources of information.

The BIDScoin toolkit was used to successfully coin over 1000 subject source level datasets from various research projects conducted within the Donders Institute. This included datasets with source level data in DICOM format, with fieldmap data, mutli-echo echo, multi-coil data, PET data and various anatomical, diffusion and functional MRI scans.

## Preferred Session
Neuroscience toolkit

**Comment by TimVanMourik** [comment]
Hi @marcelzwiers,  I’m happy to tell you that we’d like to host your lightning talk in the OSR in the **neuroscience toolkit** session. This will be a talk of 5 minutes + 5 minutes of questions. We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master/) by means of a Pull Request to this repository, preferably but not necessarily before the presentation.

**Comment by TimVanMourik** [comment]
Presentation added in #50
