### ISSUE TITLE
niQC SIG Meeting

### ISSUE THREAD

**Issue by raamana** [ohbm/OpenScienceRoom2019#30]
**Topic**
Neuroimaging Quality Control SIG meeting
More info here: https://incf.github.io/niQC/

**Main organiser**
Pradeep Reddy Raamana
and the niQC SIG.

**Preferred time slots**
TBD - please indicate what is possible and/or available

**Tag other attendees**

**Open to all?**
**Yes**. 
Both New and existing members

**Additional Context**
 - Meet and greet for the current members
 - Raising awareness in the community

#

Bookings will be coordinated by @TimVanMourik. The schedule is available [here](https://calendar.google.com/calendar?cid=anJjNGh1dXFtODkyazVpbzk3OXF2YmM2N29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

**Comment by TimVanMourik** [comment]
Hi @raamana, basically Monday morning and Wednesday afternoon are completely free. How about Wednesday 15:00?

**Comment by raamana** [comment]
Thanks Tim, let me double check with my group before confirming it. what about Tuesday 11am?

Also, what’s the capacity of the room?

**Comment by TimVanMourik** [comment]
Tuesday morning the OSR program starts at 10:30, see [schedule](https://github.com/ohbm/OpenScienceRoom2019/blob/master/OSR%20Schedule.pdf). We need a little time to prepare, but until 10ish, it's all yours if you want.

It's the same room where the presentations are, so plenty of space for a meeting I'd say. I haven't got exact numbers.

**Comment by raamana** [comment]
Thanks Tim. Would we be able to use the projector for the meeting? Is there some tech setup to live stream the meeting? 

I’d like to try enable remote attendance for those who couldn’t make it to OHBM. Using another laptop from attendee to run Zoom might work too.. just checking what’s available. Thanks.

**Comment by TimVanMourik** [comment]
Hi @raamana, I asked the facility manager for recording and/or streaming setups, but unfortunately we don't have them this year 😞 So meetings will have to take care of their own Zoom/Skype/Hangouts/whatever setup. Sorry!

**Comment by raamana** [comment]
No worries, thanks for confirming. I assume there will be Wifi, although ethernet might not exist, yes?

**Comment by TimVanMourik** [comment]
Absolutely there will be Wifi! Although I've got no idea about its stability with X-thousands of people around. Good point, I'm not sure if there's an ethernet connection. I will inquire.
