### ISSUE TITLE
Demo: C-PAC

### ISSUE THREAD

**Issue by anibalsolon** [ohbm/OpenScienceRoom2019#32]
**Title**
Configurable Pipeline for the Analysis of Connectomes

**Presentor and Affiliation**
Anibal Solon Heinsfeld - Child Mind Institute

**Collaborators**
@sgiavasis

**Github Link (if applicable)**
https://github.com/FCP-INDI/C-PAC

**Abstract (max. 200 words):**
A configurable, open-source, Nipype-based, automated processing pipeline for resting state fMRI data. Designed for use by both novice users and experts, C-PAC brings the power, flexibility, and elegance of Nipype to users in a plug-and-play fashion; no programming required.
In this demo, we want to introduce how to easily go from raw fMRI data to preprocessed data, with several derivatives and analyses. We will go through the installation, data setup, pipeline options and running it with Docker.

**Preferred Session**
3. Demo: New advances in open neuroimaging methods

**Additional Context**

**Comment by TimVanMourik** [comment]
Hi @anibalsolon, I am very sorry, but your application was after the deadline and we already had too many applications. You're the high up on the waiting list and we're happy to host your talk if anyone drops out, in which case I will contact you.

**Comment by anibalsolon** [comment]
Thanks @TimVanMourik !
