### ISSUE TITLE
Clinica: software platform for clinical neuroimaging studies

### ISSUE THREAD

**Issue by alexandreroutier** [ohbm/OpenScienceRoom2019#33]
**Title**
Clinica: software platform for clinical neuroimaging studies

**Presentor and Affiliation**
Ninon Burgos, CNRS
Alexandre Routier, Inria

**Collaborators**
Olivier Colliot (@oliviercolliot)
Arnaud Marcoux (@arnaudmarcoux)
Jorge Samper Gonzalez (@jsampergonzalez)
Junhao Wen (@anbai106)
Simona Bottani (@SimonaBottani)
Elina Thibeau--Sutre (@14thibea)

**Github Link (if applicable)**
https://github.com/aramis-lab/clinica
http://www.clinica.run

**Abstract (max. 200 words):**
Clinica is an open source software platform designed to make clinical neuroscience studies easier and more reproducible. Clinica aims for researchers to spend less time on data management and processing, perform reproducible evaluations of their methods, and easily share data and results within their institution and with external collaborators.

Clinica relies on the brain imaging data structure (BIDS) for the organization of raw neuroimaging datasets and on tools written by the community to build complex pipelines for the analysis of neuroimaging data. It also provides converters of public neuroimaging datasets to BIDS (ADNI/AIBL/OASIS), statistical analysis and machine learning algorithms. Clinica can handle MRI (T1w/DWI/fMRI) and PET data. Processed data include image-valued scalar fields (e.g. tissue probability maps), surface-based scalar fields (e.g. cortical thickness maps) or scalar outputs (e.g. regional averages). They also follow the ClinicA Processed Structure (CAPS) format which shares the same philosophy as BIDS. Standardized organization of raw and processed neuroimaging files facilitates the execution of pipelines and the integration of processed data into statistics or machine learning frameworks.

The target audience of Clinica is neuroscientists or clinicians conducting clinical neuroscience studies involving multimodal imaging, and researchers developing advanced machine learning algorithms.

**Preferred Session**
3. Collaborative research and team science

**Additional Context**
Documentation: http://www.clinica.run/doc
Installation: `conda create --name clinicaEnv python=3.6 clinica -c Aramislab -c conda-forge`

**Comment by TimVanMourik** [comment]
Hi @alexandreroutier! That looks like pretty cool stuff and there's still a spot left in that session. I'd be happy to give it to you. That would be a 5 minute talk plus 5 minute questions. The link to your platform (both the platform and the docs) is broken though, could you please update that? And is the platform itself targeted at collaborative research?

**Comment by TimVanMourik** [comment]
*Ah, it looks like the website is not setup to deal with an 'apex domain', so when you add www to the link it works.

**Comment by alexandreroutier** [comment]
Thank you for your quick answer. There is indeed an issue with clinica.run without www. We need to fix this ASAP. In the meantime, I have edited the first post.

**Comment by TimVanMourik** [comment]
Presentation uploaded in #55
