### ISSUE TITLE
Multi-Echo fMRI not-SIG Meeting

### ISSUE THREAD

**Issue by smoia** [ohbm/OpenScienceRoom2019#38]
**Topic**
Multi-Echo fMRI: updates on last year's development in the field and propositions up to OHBM 2020

**Main organiser**
Stefano Moia (@smoia) & Elizabeth DuPre (@emdupre)

**Preferred time slots**
Wednesday 12 16h15-17h30

**Tag other attendees** 
@KirstieJane @tsalo @handwerkerd @javiergcas @CesarCaballeroGaudes
@jsheunis @eurunuela

**Open to**
Everyone that [has an interest in / wants to hear about / work with / work on / develop for / ... ] Multi-Echo fMRI (whishfully all)

**Additional Context**
Dear all,
after meeting and writing code together during the Hackathon, we wanted to propose a meeting to see each other, discuss what happened in the last year, propose things we would like to be done with ME, and possibly have a common roadmap toward OHBM 2020.
Hope you will be able to attend!

#

Bookings will be coordinated by @TimVanMourik. The schedule is available [here](https://calendar.google.com/calendar?cid=anJjNGh1dXFtODkyazVpbzk3OXF2YmM2N29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

**Comment by TimVanMourik** [comment]
Hi @smoia! Awesome, I added it to the [agenda](https://calendar.google.com/calendar?cid=anJjNGh1dXFtODkyazVpbzk3OXF2YmM2N29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ).

**Comment by smoia** [comment]
Thank you @TimVanMourik !

**Comment by CesarCaballeroGaudes** [comment]
Are you planning to accept skype talks during the meeting? If so, I will try to join. Otherwise @eurunuela and @smoia can definitely give me detail feedback when they come back at BCBL

**Comment by eurunuela** [comment]
I guess we could do that but I don’t know if the WiFi will be fast enough to handle it. My phone call with @smoia yesterday was pretty bad due to the poor WiFi connection in Rome. We’ll surely make you know @CesarCaballeroGaudes !

**Comment by smoia** [comment]
@KirstieJane @tsalo @handwerkerd @javiergcas @CesarCaballeroGaudes
@jsheunis @eurunuela, if you know any other persion that might be interested in joining this meeting, please contact them to suggest attendance!

**Comment by TimVanMourik** [comment]
Closing this discussion issue, but feel free to add more content, links, or documents (PR) to document what's been discussed!
