### ISSUE TITLE
Why haven't I shared my data (yet)?

### ISSUE THREAD

**Issue by Helene-ve** [ohbm/OpenScienceRoom2019#44]
**Topic**
Open, interactive discussion about problems and difficulties that may hinder data sharing.

When we asked 200 authors of executive function network papers to share their image data for our network name meta-analysis, we got less than 40% of the data after much effort. This, of course, affected several analyses we planned. We understand that it may be more difficult for researchers in smaller labs, working with smaller data sets to commit to data sharing, and wish to talk with you about what hinders you!

**Main organiser**
Helene van Ettinger-Veenstra

**Preferred time slots**
Wed 11:50-12:20

**Open to all?**
OPEN TO EVERYONE! Especially researchers that find it difficult to share their data, and people that are interested in listening to their reasons why.

**Additional Context**
The meta-analysis that we performed can be found on poster [TH308](https://drive.google.com/open?id=14kp3-_4_B7ZhjHV_mpKSpqFdv_kZl-Sl)

Bookings will be coordinated by @TimVanMourik. The schedule is available [here](https://calendar.google.com/calendar?cid=anJjNGh1dXFtODkyazVpbzk3OXF2YmM2N29AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

**Comment by TimVanMourik** [comment]
Hi @Helene-ve, is it OK if I put it down for 12:00-12:45? That's now in the schedule.

**Comment by Helene-ve** [comment]
That’s fine!

**Comment by TimVanMourik** [comment]
Closing this discussion as an issue, but feel free to add more content, links, or documents (PR) to document what's been discussed!
