### ISSUE TITLE
NITRC Overview

### ISSUE THREAD

**Issue by ninapreuss** [ohbm/OpenScienceRoom2019#46]
**Title**
NeuroImaging Tools & Resources Collaboratory (NITRC)

**Presentor and Affiliation**
Nina Preuss, Co-PI, Preuss Enterprises, Inc.
David Kennedy, Co-PI, UMass

**Collaborators**
Christian Haselgrove, UMass
Al Crowley, TCG
Matt Travers, TCG
Abby Paulson, Paulson Ventures

**Github Link (if applicable)**

**Abstract (max. 200 words):**
Aim of Investigation: NeuroImaging Tools and Resources Collaboratory (NITRC) is a neuroinformatics knowledge environment for MR, PET/SPECT, CT, EEG/MEG, optical imaging, clinical neuroinformatics, computational neuroscience, and imaging genomics tools and resources.  
 
Methods: Initiated in 2006 through the NIH Blueprint for Neuroscience Research, NITRC’s mission is to foster a user-friendly knowledge environment for the neuroinformatics community. By continuing to identify existing software tools and resources valuable to this community, NITRC’s goal is to support its researchers dedicated to enhancing, adopting, distributing, and contributing to the evolution of neuroinformatics analysis software, data, and compute resources.
 
Results: Located on the web at www.nitrc.org, the Resources Registry (NITRC-R) promotes software tools and resources, vocabularies, test data, and databases, thereby extending the impact of previously funded, neuroimaging informatics contributions to a broader community.  NITRC-R gives researchers greater and more efficient access to the tools and resources they need, better categorizing and organizing existing tools and resources, facilitating interactions between researchers and developers, and promoting better use through enhanced documentation and tutorials—all while directing the most recent upgrades, forums, and updates. All services freely downloadable, NITRC-R offers over 1,090 public resources; NITRC-Image Repository (NITRC-IR) offers 16 data projects, 10,860 subjects, and 12,440 imaging sessions, and NITRC Computational Environment (NITRC-CE) provides cloud-based computation services downloadable to local machines or via commercial cloud providers such as Amazon Web Services. 
 
Conclusions: In summary, NITRC is now an established knowledge environment for the neuroimaging community where tools and resources are presented in a coherent and synergistic environment.  NITRC is a trusted source for the identification of resources in this global community. With over 6,230 citations on Google Scholar, NITRC has supported over 26,000 registered users, served up 10.8 million total, and of that, 9.7 million data downloads, to over 1.1 million users generating 2.5 million sessions. In addition to untold downloaded Virtual Machines, NITRC-CE currently supports over 180 subscriptions on AWS Marketplace running over 216,400 compute hours.  We encourage the neuroinformatics community to continue providing valuable resources, design and content feedback and to utilize these resources in support of data sharing requirements, software dissemination and cost-effective computational performance.
**Preferred Session**

**Additional Context**
NITRC may be familiar to most, but are you up to date with recent functionality, software and data uploads, and our latest NITRC-CE Lite (docker) instance?

**Comment by TimVanMourik** [comment]
Presentation uploaded in #43
