### ISSUE TITLE
knitr for neuroimagers

### ISSUE THREAD

**Issue by jaetzel** [ohbm/OpenScienceRoom2019#6]
**Title**
knitr for neuroimagers

**Presentor and Affiliation**
Jo Etzel, Washington University in St. Louis (USA)

**Collaborators**

**Github Link (if applicable)**

**Abstract (max. 200 words):**
This will be a short presentation about how [knitr](https://yihui.name/knitr/), a report generating library for R, can be used for generating and displaying many neuroimaging analysis results, from quality control images through GLM or MVPA results. I’ll introduce [my functions](https://mvpa.blogspot.com/2018/06/tutorial-plotting-gifti-images-in-r.html) for displaying NIfTI and gifti images in knitr documents. We have found knitr to both save time (e.g., over copy-pasting images into a word document) and to reduce errors (e.g., the source of a copy-pasted image is lost, but the full path is preserved in a knitr document). I will also point out situations when report-generating strategies like knitr (or the python equivalents) can be preferable to live notebooks. 

**Preferred Session**
Neuroscience toolkit

**Additional Context**

**Comment by TimVanMourik** [comment]
Hi @jaetzel, I’m happy to tell you that we’d like to host your lightning talk in the OSR in the **neuroscience toolkit** session. This will be a talk of 5 minutes + 5 minutes of questions. We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master/presentations), preferably but not necessarily before the presentation.

**Comment by TimVanMourik** [comment]
Hi @jaetzel, thanks for the email with the PDF. I added it in 35aea36
