### ISSUE TITLE
Talk Application: Efficiently editing sub-millimeter segmentations using interactive 2D histograms in 7 Tesla MRI

### ISSUE THREAD

**Issue by ofgulban** [ohbm/OpenScienceRoom2019#8]
**Title**
Efficiently editing sub-millimeter segmentations using interactive 2D histograms in 7 Tesla MRI

**Presentor and Affiliation**
- Omer Faruk Gulban, _Department of Cognitive Neuroscience, Faculty of Psychology and Neuroscience, Maastricht University_ ([ORCID](http://orcid.org/0000-0001-7761-3727))
- Marian Schneider,  _Department of Cognitive Neuroscience, Faculty of Psychology and Neuroscience, Maastricht University_ ([ORCID](http://orcid.org/0000-0003-3192-5316))

**Collaborators**
- Federico De Martino; _Department of Cognitive Neuroscience, Faculty of Psychology and Neuroscience, Maastricht University; Center for Magnetic Resonance Research, University of Minnesota, Minneapolis, United States of America_
- Ingo Marquardt,  _Department of Cognitive Neuroscience, Faculty of Psychology and Neuroscience, Maastricht University_ ([ORCID](http://orcid.org/0000-0001-5178-9951))

**Github Link (if applicable)**
https://github.com/ofgulban/segmentator & [wiki](https://github.com/ofgulban/segmentator/wiki)

**Abstract (max. 200 words):**
High-resolution (functional) magnetic resonance imaging (MRI) at ultra high magnetic fields (7 Tesla and above) enables researchers to study how anatomical and functional properties change within the cortical ribbon, along surfaces and across layers. These studies require an accurate delineation of the gray matter ribbon, which often suffers from inclusion of blood vessels, dura mater and other non-brain tissue. Residual segmentation errors are commonly corrected by manually browsing the data slice-by-slice. This task becomes increasingly laborious and prone to error at higher resolutions since both work and error scale with the number of voxels. Here we will present a method that speeds up correcting mislabeled, non-brain voxels by representing 3D anatomical images in 2D histograms. This 2D histogram is constructed from image intensity and gradient magnitude derived from it ([see our paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0198335)). We will demo our openly accessible Python implementation to show how it can be used after running conventional segmentation algorithms. We will also demonstrate a few cases in which our method would fail to lay an outline for future directions.

**Preferred Session**
3. Demo: New advances in open neuroimaging methods

**Additional Context**
segmentation, ultra-high field MRI, 7 Tesla, layer-MRI, vessels, cortical gray matter, submillimeter resolution

**Comment by TimVanMourik** [comment]
Hi @ofgulban, I’m happy to tell you that we’d like to host your lightning talk in the OSR in the **neuroscience toolkit** session. This will be a talk of 5 minutes + 5 minutes of questions. We’ll update the program in the ReadMe.md shortly. We were unfortunately unable to give you a slot in your preferred session due to the high number of applications.

We’d much appreciate it if you could submit presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master/) by means of a Pull Request to this repository, preferably but not necessarily before the presentation.

**Comment by MSchnei** [comment]
Presentation link:
https://docs.google.com/presentation/d/1-wgWLXeQFuCZMl7_qM_lDK3P85PMHCXPxI1687urRkg/edit?usp=sharing

**Comment by TimVanMourik** [comment]
Presentation uploaded in #48
