### ISSUE TITLE
Statistical methods for studying population of connectomes

### ISSUE THREAD

**Issue by j1c** [ohbm/OpenScienceRoom2019#9]
**Title**
Statistical methods for studying population of connectomes

**Presentor and Affiliation**
Jaewon Chung
Department of Biomedical Engineering, Johns Hopkins University
Baltimore, Maryland, USA

**Collaborators**
@jovo @bdpedigo @hhelm10

**Github Link (if applicable)**
[GraSPy](https://github.com/neurodata/graspy)

**Abstract (max. 200 words):**
Brains can be modelled as connectomes, or graphs, where nodes represent regions of interest (ROIs) and edges represent strength of connection bewteen ROIs. Traditional statistical methods for studying connectomes ignore the spatial arrangement of the nodes, and is not utilizing all of the information available. *GraSPy* fills an important gap in studying connectomes by providing flexible and easy-to-use algorithms specifically designed for analyzing and understanding population of graphs with a *scikit-learn* compliant API. Live demo will provide ways of analyzing population of connectomes from individual subject level to node level. 

**Preferred Session**
Demo: New advances in open neuroimaging methods

**Additional Context**

**Comment by TimVanMourik** [comment]
Hi @j1c, I’m happy to tell you that we’d like to host your presentation as a demo/tutorial talk in the OSR in the **Demo: New advances in open neuroimaging methods** session. This will be a talk of 20 minutes + 5 minutes of questions. We’ll update the program in the ReadMe.md shortly. We’d much appreciate it if you could submit slides and other presentation material to the [presentations folder](https://github.com/ohbm/OpenScienceRoom2019/tree/master/) by means of a Pull Request to this repository, preferably but not necessarily before the presentation.

**Comment by jovo** [comment]
wow, that's huge news! @j1c and i will be there!

**Comment by j1c** [comment]
@TimVanMourik Hi Tim. What kind of resources will be available for the live demo? i.e. will we use our own laptops, etc..

**Comment by TimVanMourik** [comment]
There will be a standard (almost certainly Windows) laptop that's hooked up to the projector, or HDMI (and probably also DVI) connectors to your own laptop. Is there anything specific you'd like to know?

**Comment by TimVanMourik** [comment]
Thanks for the presentation! 

Presentation uploaded in #49!
